server:
    port: 8888

spring:
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://localhost:3306/encore?useUnicode=true
        username: root
        password: 123456789

mybatis:
    mapper-locations: mappers/*.xml